<?php



/**
 * This class defines the structure of the 'jenkins_run' table.
 *
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Tue Feb  7 12:32:23 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class JenkinsRunTableMap extends TableMap
{

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.JenkinsRunTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
		// attributes
		$this->setName('jenkins_run');
		$this->setPhpName('JenkinsRun');
		$this->setClassname('JenkinsRun');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('JENKINS_GROUP_RUN_ID', 'JenkinsGroupRunId', 'INTEGER', 'jenkins_group_run', 'ID', true, 11, null);
		$this->addColumn('JOB_NAME', 'JobName', 'CHAR', true, 30, null);
		$this->addColumn('JOB_BUILD_NUMBER', 'JobBuildNumber', 'INTEGER', false, 11, null);
		$this->addColumn('GIT_BRANCH', 'GitBranch', 'CHAR', true, 32, null);
		$this->addColumn('LAUNCHED', 'Launched', 'INTEGER', true, 1, 1);
		$this->addColumn('PARAMETERS', 'Parameters', 'LONGVARCHAR', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
		$this->addRelation('JenkinsGroupRun', 'JenkinsGroupRun', RelationMap::MANY_TO_ONE, array('jenkins_group_run_id' => 'id', ), 'RESTRICT', null);
	} // buildRelations()

	/**
	 *
	 * Gets the list of behaviors registered for this table
	 *
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // JenkinsRunTableMap
