<?php



/**
 * This class defines the structure of the 'jenkins_group_run' table.
 *
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Tue Feb  7 12:32:23 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class JenkinsGroupRunTableMap extends TableMap
{

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.JenkinsGroupRunTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
		// attributes
		$this->setName('jenkins_group_run');
		$this->setPhpName('JenkinsGroupRun');
		$this->setClassname('JenkinsGroupRun');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('DATE', 'Date', 'DATE', true, null, null);
		$this->addColumn('USER_ID', 'UserId', 'CHAR', true, 36, null);
		$this->addColumn('LABEL', 'Label', 'CHAR', true, 100, null);
		$this->addColumn('GIT_BRANCH', 'GitBranch', 'CHAR', true, 32, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
		$this->addRelation('JenkinsRun', 'JenkinsRun', RelationMap::ONE_TO_MANY, array('id' => 'jenkins_group_run_id', ), 'RESTRICT', null, 'JenkinsRuns');
	} // buildRelations()

	/**
	 *
	 * Gets the list of behaviors registered for this table
	 *
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // JenkinsGroupRunTableMap
