<?php


/**
 * Base class that represents a query for the 'jenkins_group_run' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Tue Feb  7 12:32:23 2012
 *
 * @method     JenkinsGroupRunQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     JenkinsGroupRunQuery orderByDate($order = Criteria::ASC) Order by the date column
 * @method     JenkinsGroupRunQuery orderByUserId($order = Criteria::ASC) Order by the user_id column
 * @method     JenkinsGroupRunQuery orderByLabel($order = Criteria::ASC) Order by the label column
 * @method     JenkinsGroupRunQuery orderByGitBranch($order = Criteria::ASC) Order by the git_branch column
 *
 * @method     JenkinsGroupRunQuery groupById() Group by the id column
 * @method     JenkinsGroupRunQuery groupByDate() Group by the date column
 * @method     JenkinsGroupRunQuery groupByUserId() Group by the user_id column
 * @method     JenkinsGroupRunQuery groupByLabel() Group by the label column
 * @method     JenkinsGroupRunQuery groupByGitBranch() Group by the git_branch column
 *
 * @method     JenkinsGroupRunQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     JenkinsGroupRunQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     JenkinsGroupRunQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     JenkinsGroupRunQuery leftJoinJenkinsRun($relationAlias = null) Adds a LEFT JOIN clause to the query using the JenkinsRun relation
 * @method     JenkinsGroupRunQuery rightJoinJenkinsRun($relationAlias = null) Adds a RIGHT JOIN clause to the query using the JenkinsRun relation
 * @method     JenkinsGroupRunQuery innerJoinJenkinsRun($relationAlias = null) Adds a INNER JOIN clause to the query using the JenkinsRun relation
 *
 * @method     JenkinsGroupRun findOne(PropelPDO $con = null) Return the first JenkinsGroupRun matching the query
 * @method     JenkinsGroupRun findOneOrCreate(PropelPDO $con = null) Return the first JenkinsGroupRun matching the query, or a new JenkinsGroupRun object populated from the query conditions when no match is found
 *
 * @method     JenkinsGroupRun findOneById(int $id) Return the first JenkinsGroupRun filtered by the id column
 * @method     JenkinsGroupRun findOneByDate(string $date) Return the first JenkinsGroupRun filtered by the date column
 * @method     JenkinsGroupRun findOneByUserId(string $user_id) Return the first JenkinsGroupRun filtered by the user_id column
 * @method     JenkinsGroupRun findOneByLabel(string $label) Return the first JenkinsGroupRun filtered by the label column
 * @method     JenkinsGroupRun findOneByGitBranch(string $git_branch) Return the first JenkinsGroupRun filtered by the git_branch column
 *
 * @method     array findById(int $id) Return JenkinsGroupRun objects filtered by the id column
 * @method     array findByDate(string $date) Return JenkinsGroupRun objects filtered by the date column
 * @method     array findByUserId(string $user_id) Return JenkinsGroupRun objects filtered by the user_id column
 * @method     array findByLabel(string $label) Return JenkinsGroupRun objects filtered by the label column
 * @method     array findByGitBranch(string $git_branch) Return JenkinsGroupRun objects filtered by the git_branch column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseJenkinsGroupRunQuery extends ModelCriteria
{
	
	/**
	 * Initializes internal state of BaseJenkinsGroupRunQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'JenkinsGroupRun', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new JenkinsGroupRunQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    JenkinsGroupRunQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof JenkinsGroupRunQuery) {
			return $criteria;
		}
		$query = new JenkinsGroupRunQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key.
	 * Propel uses the instance pool to skip the database if the object exists.
	 * Go fast if the query is untouched.
	 *
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    JenkinsGroupRun|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ($key === null) {
			return null;
		}
		if ((null !== ($obj = JenkinsGroupRunPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
			// the object is alredy in the instance pool
			return $obj;
		}
		if ($con === null) {
			$con = Propel::getConnection(JenkinsGroupRunPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		$this->basePreSelect($con);
		if ($this->formatter || $this->modelAlias || $this->with || $this->select
		 || $this->selectColumns || $this->asColumns || $this->selectModifiers
		 || $this->map || $this->having || $this->joins) {
			return $this->findPkComplex($key, $con);
		} else {
			return $this->findPkSimple($key, $con);
		}
	}

	/**
	 * Find object by primary key using raw SQL to go fast.
	 * Bypass doSelect() and the object formatter by using generated code.
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con A connection object
	 *
	 * @return    JenkinsGroupRun A model object, or null if the key is not found
	 */
	protected function findPkSimple($key, $con)
	{
		$sql = 'SELECT `ID`, `DATE`, `USER_ID`, `LABEL`, `GIT_BRANCH` FROM `jenkins_group_run` WHERE `ID` = :p0';
		try {
			$stmt = $con->prepare($sql);
			$stmt->bindValue(':p0', $key, PDO::PARAM_INT);
			$stmt->execute();
		} catch (Exception $e) {
			Propel::log($e->getMessage(), Propel::LOG_ERR);
			throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
		}
		$obj = null;
		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$obj = new JenkinsGroupRun();
			$obj->hydrate($row);
			JenkinsGroupRunPeer::addInstanceToPool($obj, (string) $row[0]);
		}
		$stmt->closeCursor();

		return $obj;
	}

	/**
	 * Find object by primary key.
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con A connection object
	 *
	 * @return    JenkinsGroupRun|array|mixed the result, formatted by the current formatter
	 */
	protected function findPkComplex($key, $con)
	{
		// As the query uses a PK condition, no limit(1) is necessary.
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		$stmt = $criteria
			->filterByPrimaryKey($key)
			->doSelect($con);
		return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
		}
		$this->basePreSelect($con);
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		$stmt = $criteria
			->filterByPrimaryKeys($keys)
			->doSelect($con);
		return $criteria->getFormatter()->init($criteria)->format($stmt);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    JenkinsGroupRunQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(JenkinsGroupRunPeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    JenkinsGroupRunQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(JenkinsGroupRunPeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the id column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterById(1234); // WHERE id = 1234
	 * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
	 * $query->filterById(array('min' => 12)); // WHERE id > 12
	 * </code>
	 *
	 * @param     mixed $id The value to use as filter.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    JenkinsGroupRunQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(JenkinsGroupRunPeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query on the date column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByDate('2011-03-14'); // WHERE date = '2011-03-14'
	 * $query->filterByDate('now'); // WHERE date = '2011-03-14'
	 * $query->filterByDate(array('max' => 'yesterday')); // WHERE date > '2011-03-13'
	 * </code>
	 *
	 * @param     mixed $date The value to use as filter.
	 *              Values can be integers (unix timestamps), DateTime objects, or strings.
	 *              Empty strings are treated as NULL.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    JenkinsGroupRunQuery The current query, for fluid interface
	 */
	public function filterByDate($date = null, $comparison = null)
	{
		if (is_array($date)) {
			$useMinMax = false;
			if (isset($date['min'])) {
				$this->addUsingAlias(JenkinsGroupRunPeer::DATE, $date['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($date['max'])) {
				$this->addUsingAlias(JenkinsGroupRunPeer::DATE, $date['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(JenkinsGroupRunPeer::DATE, $date, $comparison);
	}

	/**
	 * Filter the query on the user_id column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByUserId('fooValue');   // WHERE user_id = 'fooValue'
	 * $query->filterByUserId('%fooValue%'); // WHERE user_id LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $userId The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    JenkinsGroupRunQuery The current query, for fluid interface
	 */
	public function filterByUserId($userId = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($userId)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $userId)) {
				$userId = str_replace('*', '%', $userId);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(JenkinsGroupRunPeer::USER_ID, $userId, $comparison);
	}

	/**
	 * Filter the query on the label column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByLabel('fooValue');   // WHERE label = 'fooValue'
	 * $query->filterByLabel('%fooValue%'); // WHERE label LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $label The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    JenkinsGroupRunQuery The current query, for fluid interface
	 */
	public function filterByLabel($label = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($label)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $label)) {
				$label = str_replace('*', '%', $label);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(JenkinsGroupRunPeer::LABEL, $label, $comparison);
	}

	/**
	 * Filter the query on the git_branch column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByGitBranch('fooValue');   // WHERE git_branch = 'fooValue'
	 * $query->filterByGitBranch('%fooValue%'); // WHERE git_branch LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $gitBranch The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    JenkinsGroupRunQuery The current query, for fluid interface
	 */
	public function filterByGitBranch($gitBranch = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($gitBranch)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $gitBranch)) {
				$gitBranch = str_replace('*', '%', $gitBranch);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(JenkinsGroupRunPeer::GIT_BRANCH, $gitBranch, $comparison);
	}

	/**
	 * Filter the query by a related JenkinsRun object
	 *
	 * @param     JenkinsRun $jenkinsRun  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    JenkinsGroupRunQuery The current query, for fluid interface
	 */
	public function filterByJenkinsRun($jenkinsRun, $comparison = null)
	{
		if ($jenkinsRun instanceof JenkinsRun) {
			return $this
				->addUsingAlias(JenkinsGroupRunPeer::ID, $jenkinsRun->getJenkinsGroupRunId(), $comparison);
		} elseif ($jenkinsRun instanceof PropelCollection) {
			return $this
				->useJenkinsRunQuery()
				->filterByPrimaryKeys($jenkinsRun->getPrimaryKeys())
				->endUse();
		} else {
			throw new PropelException('filterByJenkinsRun() only accepts arguments of type JenkinsRun or PropelCollection');
		}
	}

	/**
	 * Adds a JOIN clause to the query using the JenkinsRun relation
	 *
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    JenkinsGroupRunQuery The current query, for fluid interface
	 */
	public function joinJenkinsRun($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('JenkinsRun');

		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}

		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'JenkinsRun');
		}

		return $this;
	}

	/**
	 * Use the JenkinsRun relation JenkinsRun object
	 *
	 * @see       useQuery()
	 *
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    JenkinsRunQuery A secondary query class using the current class as primary query
	 */
	public function useJenkinsRunQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinJenkinsRun($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'JenkinsRun', 'JenkinsRunQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     JenkinsGroupRun $jenkinsGroupRun Object to remove from the list of results
	 *
	 * @return    JenkinsGroupRunQuery The current query, for fluid interface
	 */
	public function prune($jenkinsGroupRun = null)
	{
		if ($jenkinsGroupRun) {
			$this->addUsingAlias(JenkinsGroupRunPeer::ID, $jenkinsGroupRun->getId(), Criteria::NOT_EQUAL);
		}

		return $this;
	}

} // BaseJenkinsGroupRunQuery