<?php


/**
 * Base class that represents a row from the 'jenkins_run' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Tue Feb  7 12:32:23 2012
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseJenkinsRun extends BaseObject  implements Persistent
{

	/**
	 * Peer class name
	 */
	const PEER = 'JenkinsRunPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        JenkinsRunPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the jenkins_group_run_id field.
	 * @var        int
	 */
	protected $jenkins_group_run_id;

	/**
	 * The value for the job_name field.
	 * @var        string
	 */
	protected $job_name;

	/**
	 * The value for the job_build_number field.
	 * @var        int
	 */
	protected $job_build_number;

	/**
	 * The value for the git_branch field.
	 * @var        string
	 */
	protected $git_branch;

	/**
	 * The value for the launched field.
	 * Note: this column has a database default value of: 1
	 * @var        int
	 */
	protected $launched;

	/**
	 * The value for the parameters field.
	 * @var        string
	 */
	protected $parameters;

	/**
	 * @var        JenkinsGroupRun
	 */
	protected $aJenkinsGroupRun;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->launched = 1;
	}

	/**
	 * Initializes internal state of BaseJenkinsRun object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [jenkins_group_run_id] column value.
	 * 
	 * @return     int
	 */
	public function getJenkinsGroupRunId()
	{
		return $this->jenkins_group_run_id;
	}

	/**
	 * Get the [job_name] column value.
	 * 
	 * @return     string
	 */
	public function getJobName()
	{
		return $this->job_name;
	}

	/**
	 * Get the [job_build_number] column value.
	 * 
	 * @return     int
	 */
	public function getJobBuildNumber()
	{
		return $this->job_build_number;
	}

	/**
	 * Get the [git_branch] column value.
	 * 
	 * @return     string
	 */
	public function getGitBranch()
	{
		return $this->git_branch;
	}

	/**
	 * Get the [launched] column value.
	 * 
	 * @return     int
	 */
	public function getLaunched()
	{
		return $this->launched;
	}

	/**
	 * Get the [parameters] column value.
	 * 
	 * @return     string
	 */
	public function getParameters()
	{
		return $this->parameters;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     JenkinsRun The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = JenkinsRunPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [jenkins_group_run_id] column.
	 * 
	 * @param      int $v new value
	 * @return     JenkinsRun The current object (for fluent API support)
	 */
	public function setJenkinsGroupRunId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->jenkins_group_run_id !== $v) {
			$this->jenkins_group_run_id = $v;
			$this->modifiedColumns[] = JenkinsRunPeer::JENKINS_GROUP_RUN_ID;
		}

		if ($this->aJenkinsGroupRun !== null && $this->aJenkinsGroupRun->getId() !== $v) {
			$this->aJenkinsGroupRun = null;
		}

		return $this;
	} // setJenkinsGroupRunId()

	/**
	 * Set the value of [job_name] column.
	 * 
	 * @param      string $v new value
	 * @return     JenkinsRun The current object (for fluent API support)
	 */
	public function setJobName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->job_name !== $v) {
			$this->job_name = $v;
			$this->modifiedColumns[] = JenkinsRunPeer::JOB_NAME;
		}

		return $this;
	} // setJobName()

	/**
	 * Set the value of [job_build_number] column.
	 * 
	 * @param      int $v new value
	 * @return     JenkinsRun The current object (for fluent API support)
	 */
	public function setJobBuildNumber($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->job_build_number !== $v) {
			$this->job_build_number = $v;
			$this->modifiedColumns[] = JenkinsRunPeer::JOB_BUILD_NUMBER;
		}

		return $this;
	} // setJobBuildNumber()

	/**
	 * Set the value of [git_branch] column.
	 * 
	 * @param      string $v new value
	 * @return     JenkinsRun The current object (for fluent API support)
	 */
	public function setGitBranch($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->git_branch !== $v) {
			$this->git_branch = $v;
			$this->modifiedColumns[] = JenkinsRunPeer::GIT_BRANCH;
		}

		return $this;
	} // setGitBranch()

	/**
	 * Set the value of [launched] column.
	 * 
	 * @param      int $v new value
	 * @return     JenkinsRun The current object (for fluent API support)
	 */
	public function setLaunched($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->launched !== $v) {
			$this->launched = $v;
			$this->modifiedColumns[] = JenkinsRunPeer::LAUNCHED;
		}

		return $this;
	} // setLaunched()

	/**
	 * Set the value of [parameters] column.
	 * 
	 * @param      string $v new value
	 * @return     JenkinsRun The current object (for fluent API support)
	 */
	public function setParameters($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->parameters !== $v) {
			$this->parameters = $v;
			$this->modifiedColumns[] = JenkinsRunPeer::PARAMETERS;
		}

		return $this;
	} // setParameters()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->launched !== 1) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->jenkins_group_run_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->job_name = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->job_build_number = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->git_branch = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->launched = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->parameters = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			return $startcol + 7; // 7 = JenkinsRunPeer::NUM_HYDRATE_COLUMNS.

		} catch (Exception $e) {
			throw new PropelException("Error populating JenkinsRun object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aJenkinsGroupRun !== null && $this->jenkins_group_run_id !== $this->aJenkinsGroupRun->getId()) {
			$this->aJenkinsGroupRun = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(JenkinsRunPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = JenkinsRunPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aJenkinsGroupRun = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(JenkinsRunPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		try {
			$deleteQuery = JenkinsRunQuery::create()
				->filterByPrimaryKey($this->getPrimaryKey());
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseJenkinsRun:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			    return;
			  }
			}

			if ($ret) {
				$deleteQuery->delete($con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseJenkinsRun:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$con->commit();
				$this->setDeleted(true);
			} else {
				$con->commit();
			}
		} catch (Exception $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(JenkinsRunPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseJenkinsRun:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			  	$con->commit();
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseJenkinsRun:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				JenkinsRunPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (Exception $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aJenkinsGroupRun !== null) {
				if ($this->aJenkinsGroupRun->isModified() || $this->aJenkinsGroupRun->isNew()) {
					$affectedRows += $this->aJenkinsGroupRun->save($con);
				}
				$this->setJenkinsGroupRun($this->aJenkinsGroupRun);
			}

			if ($this->isNew() || $this->isModified()) {
				// persist changes
				if ($this->isNew()) {
					$this->doInsert($con);
				} else {
					$this->doUpdate($con);
				}
				$affectedRows += 1;
				$this->resetModified();
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Insert the row in the database.
	 *
	 * @param      PropelPDO $con
	 *
	 * @throws     PropelException
	 * @see        doSave()
	 */
	protected function doInsert(PropelPDO $con)
	{
		$modifiedColumns = array();
		$index = 0;

		$this->modifiedColumns[] = JenkinsRunPeer::ID;
		if (null !== $this->id) {
			throw new PropelException('Cannot insert a value for auto-increment primary key (' . JenkinsRunPeer::ID . ')');
		}

		 // check the columns in natural order for more readable SQL queries
		if ($this->isColumnModified(JenkinsRunPeer::ID)) {
			$modifiedColumns[':p' . $index++]  = '`ID`';
		}
		if ($this->isColumnModified(JenkinsRunPeer::JENKINS_GROUP_RUN_ID)) {
			$modifiedColumns[':p' . $index++]  = '`JENKINS_GROUP_RUN_ID`';
		}
		if ($this->isColumnModified(JenkinsRunPeer::JOB_NAME)) {
			$modifiedColumns[':p' . $index++]  = '`JOB_NAME`';
		}
		if ($this->isColumnModified(JenkinsRunPeer::JOB_BUILD_NUMBER)) {
			$modifiedColumns[':p' . $index++]  = '`JOB_BUILD_NUMBER`';
		}
		if ($this->isColumnModified(JenkinsRunPeer::GIT_BRANCH)) {
			$modifiedColumns[':p' . $index++]  = '`GIT_BRANCH`';
		}
		if ($this->isColumnModified(JenkinsRunPeer::LAUNCHED)) {
			$modifiedColumns[':p' . $index++]  = '`LAUNCHED`';
		}
		if ($this->isColumnModified(JenkinsRunPeer::PARAMETERS)) {
			$modifiedColumns[':p' . $index++]  = '`PARAMETERS`';
		}

		$sql = sprintf(
			'INSERT INTO `jenkins_run` (%s) VALUES (%s)',
			implode(', ', $modifiedColumns),
			implode(', ', array_keys($modifiedColumns))
		);

		try {
			$stmt = $con->prepare($sql);
			foreach ($modifiedColumns as $identifier => $columnName) {
				switch ($columnName) {
					case '`ID`':
						$stmt->bindValue($identifier, $this->id, PDO::PARAM_INT);
						break;
					case '`JENKINS_GROUP_RUN_ID`':
						$stmt->bindValue($identifier, $this->jenkins_group_run_id, PDO::PARAM_INT);
						break;
					case '`JOB_NAME`':
						$stmt->bindValue($identifier, $this->job_name, PDO::PARAM_STR);
						break;
					case '`JOB_BUILD_NUMBER`':
						$stmt->bindValue($identifier, $this->job_build_number, PDO::PARAM_INT);
						break;
					case '`GIT_BRANCH`':
						$stmt->bindValue($identifier, $this->git_branch, PDO::PARAM_STR);
						break;
					case '`LAUNCHED`':
						$stmt->bindValue($identifier, $this->launched, PDO::PARAM_INT);
						break;
					case '`PARAMETERS`':
						$stmt->bindValue($identifier, $this->parameters, PDO::PARAM_STR);
						break;
				}
			}
			$stmt->execute();
		} catch (Exception $e) {
			Propel::log($e->getMessage(), Propel::LOG_ERR);
			throw new PropelException(sprintf('Unable to execute INSERT statement [%s]', $sql), $e);
		}

		try {
			$pk = $con->lastInsertId();
		} catch (Exception $e) {
			throw new PropelException('Unable to get autoincrement id.', $e);
		}
		$this->setId($pk);

		$this->setNew(false);
	}

	/**
	 * Update the row in the database.
	 *
	 * @param      PropelPDO $con
	 *
	 * @see        doSave()
	 */
	protected function doUpdate(PropelPDO $con)
	{
		$selectCriteria = $this->buildPkeyCriteria();
		$valuesCriteria = $this->buildCriteria();
		BasePeer::doUpdate($selectCriteria, $valuesCriteria, $con);
	}

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aJenkinsGroupRun !== null) {
				if (!$this->aJenkinsGroupRun->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aJenkinsGroupRun->getValidationFailures());
				}
			}


			if (($retval = JenkinsRunPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = JenkinsRunPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getJenkinsGroupRunId();
				break;
			case 2:
				return $this->getJobName();
				break;
			case 3:
				return $this->getJobBuildNumber();
				break;
			case 4:
				return $this->getGitBranch();
				break;
			case 5:
				return $this->getLaunched();
				break;
			case 6:
				return $this->getParameters();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 *                    Defaults to BasePeer::TYPE_PHPNAME.
	 * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to TRUE.
	 * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
	 * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
	 *
	 * @return    array an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array(), $includeForeignObjects = false)
	{
		if (isset($alreadyDumpedObjects['JenkinsRun'][$this->getPrimaryKey()])) {
			return '*RECURSION*';
		}
		$alreadyDumpedObjects['JenkinsRun'][$this->getPrimaryKey()] = true;
		$keys = JenkinsRunPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getJenkinsGroupRunId(),
			$keys[2] => $this->getJobName(),
			$keys[3] => $this->getJobBuildNumber(),
			$keys[4] => $this->getGitBranch(),
			$keys[5] => $this->getLaunched(),
			$keys[6] => $this->getParameters(),
		);
		if ($includeForeignObjects) {
			if (null !== $this->aJenkinsGroupRun) {
				$result['JenkinsGroupRun'] = $this->aJenkinsGroupRun->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
			}
		}
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = JenkinsRunPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setJenkinsGroupRunId($value);
				break;
			case 2:
				$this->setJobName($value);
				break;
			case 3:
				$this->setJobBuildNumber($value);
				break;
			case 4:
				$this->setGitBranch($value);
				break;
			case 5:
				$this->setLaunched($value);
				break;
			case 6:
				$this->setParameters($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = JenkinsRunPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setJenkinsGroupRunId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setJobName($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setJobBuildNumber($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setGitBranch($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setLaunched($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setParameters($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(JenkinsRunPeer::DATABASE_NAME);

		if ($this->isColumnModified(JenkinsRunPeer::ID)) $criteria->add(JenkinsRunPeer::ID, $this->id);
		if ($this->isColumnModified(JenkinsRunPeer::JENKINS_GROUP_RUN_ID)) $criteria->add(JenkinsRunPeer::JENKINS_GROUP_RUN_ID, $this->jenkins_group_run_id);
		if ($this->isColumnModified(JenkinsRunPeer::JOB_NAME)) $criteria->add(JenkinsRunPeer::JOB_NAME, $this->job_name);
		if ($this->isColumnModified(JenkinsRunPeer::JOB_BUILD_NUMBER)) $criteria->add(JenkinsRunPeer::JOB_BUILD_NUMBER, $this->job_build_number);
		if ($this->isColumnModified(JenkinsRunPeer::GIT_BRANCH)) $criteria->add(JenkinsRunPeer::GIT_BRANCH, $this->git_branch);
		if ($this->isColumnModified(JenkinsRunPeer::LAUNCHED)) $criteria->add(JenkinsRunPeer::LAUNCHED, $this->launched);
		if ($this->isColumnModified(JenkinsRunPeer::PARAMETERS)) $criteria->add(JenkinsRunPeer::PARAMETERS, $this->parameters);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(JenkinsRunPeer::DATABASE_NAME);
		$criteria->add(JenkinsRunPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Returns true if the primary key for this object is null.
	 * @return     boolean
	 */
	public function isPrimaryKeyNull()
	{
		return null === $this->getId();
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of JenkinsRun (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @param      boolean $makeNew Whether to reset autoincrement PKs and make the object new.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
	{
		$copyObj->setJenkinsGroupRunId($this->getJenkinsGroupRunId());
		$copyObj->setJobName($this->getJobName());
		$copyObj->setJobBuildNumber($this->getJobBuildNumber());
		$copyObj->setGitBranch($this->getGitBranch());
		$copyObj->setLaunched($this->getLaunched());
		$copyObj->setParameters($this->getParameters());
		if ($makeNew) {
			$copyObj->setNew(true);
			$copyObj->setId(NULL); // this is a auto-increment column, so set to default value
		}
	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     JenkinsRun Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     JenkinsRunPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new JenkinsRunPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a JenkinsGroupRun object.
	 *
	 * @param      JenkinsGroupRun $v
	 * @return     JenkinsRun The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setJenkinsGroupRun(JenkinsGroupRun $v = null)
	{
		if ($v === null) {
			$this->setJenkinsGroupRunId(NULL);
		} else {
			$this->setJenkinsGroupRunId($v->getId());
		}

		$this->aJenkinsGroupRun = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the JenkinsGroupRun object, it will not be re-added.
		if ($v !== null) {
			$v->addJenkinsRun($this);
		}

		return $this;
	}


	/**
	 * Get the associated JenkinsGroupRun object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     JenkinsGroupRun The associated JenkinsGroupRun object.
	 * @throws     PropelException
	 */
	public function getJenkinsGroupRun(PropelPDO $con = null)
	{
		if ($this->aJenkinsGroupRun === null && ($this->jenkins_group_run_id !== null)) {
			$this->aJenkinsGroupRun = JenkinsGroupRunQuery::create()->findPk($this->jenkins_group_run_id, $con);
			/* The following can be used additionally to
				guarantee the related object contains a reference
				to this object.  This level of coupling may, however, be
				undesirable since it could result in an only partially populated collection
				in the referenced object.
				$this->aJenkinsGroupRun->addJenkinsRuns($this);
			 */
		}
		return $this->aJenkinsGroupRun;
	}

	/**
	 * Clears the current object and sets all attributes to their default values
	 */
	public function clear()
	{
		$this->id = null;
		$this->jenkins_group_run_id = null;
		$this->job_name = null;
		$this->job_build_number = null;
		$this->git_branch = null;
		$this->launched = null;
		$this->parameters = null;
		$this->alreadyInSave = false;
		$this->alreadyInValidation = false;
		$this->clearAllReferences();
		$this->applyDefaultValues();
		$this->resetModified();
		$this->setNew(true);
		$this->setDeleted(false);
	}

	/**
	 * Resets all references to other model objects or collections of model objects.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect
	 * objects with circular references (even in PHP 5.3). This is currently necessary
	 * when using Propel in certain daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all referrer objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

		$this->aJenkinsGroupRun = null;
	}

	/**
	 * Return the string representation of this object
	 *
	 * @return string
	 */
	public function __toString()
	{
		return (string) $this->exportTo(JenkinsRunPeer::DEFAULT_STRING_FORMAT);
	}

	/**
	 * Catches calls to virtual methods
	 */
	public function __call($name, $params)
	{
		
		// symfony_behaviors behavior
		if ($callable = sfMixer::getCallable('BaseJenkinsRun:' . $name))
		{
		  array_unshift($params, $this);
		  return call_user_func_array($callable, $params);
		}

		return parent::__call($name, $params);
	}

} // BaseJenkinsRun
