<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_guard_permission' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Jan 23 17:03:07 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfGuardPlugin.lib.model
 */
class sfGuardPermissionQuery extends BasesfGuardPermissionQuery {

} // sfGuardPermissionQuery
