<?php



/**
 * Skeleton subclass for performing query and update operations on the 'jenkins_group_run' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Fri Jan 20 17:32:29 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class JenkinsGroupRunPeer extends BaseJenkinsGroupRunPeer {

} // JenkinsGroupRunPeer
