<?php



/**
 * Skeleton subclass for performing query and update operations on the 'jenkins_group_run' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Fri Jan 20 17:32:29 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class JenkinsGroupRunPeer extends BaseJenkinsGroupRunPeer {


  /**
   * @param int            $userId
   * @param string         $gitBranch
   * @param null|PropelPDO $con
   *
   * @return JenkinsGroupRun
   */
  public static function retrieveBySfGuardUserIdAndGitBranchSlug($userId, $gitBranch, PropelPDO $con = null)
  {
    $criteria = new Criteria();
    $criteria->add(self::SF_GUARD_USER_ID, $userId);
    $criteria->add(self::GIT_BRANCH_SLUG, $gitBranch);

    return self::doSelectOne($criteria, $con);
  }

} // JenkinsGroupRunPeer
