<?php



/**
 * Skeleton subclass for performing query and update operations on the 'profile' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Tue Jan 31 08:41:25 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ProfilePeer extends BaseProfilePeer {

} // ProfilePeer
