all:
  .settings:
    enabled_modules:
      - sfGuardAuth
      - jenkins
      - default
      
    login_module:           sfGuardAuth
    login_action:           signin
     
    secure_module:          sfGuardAuth
    secure_action:          secure