# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Jenkins Khan

  has_layout:     true
  layout:         layout
  
  stylesheets:    
    #- ../css/less/bootstrap.less: {rel:  stylesheet/less }
    - less/static.css
  
  javascripts:
    #- less-1.1.3.min.js
    - jquery/jquery.js
  
  components:
    messages_flash: [default, messagesFlash]
    menu: [default, topMenu]


