# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Jenkins Khan

  has_layout:     true
  layout:         layout
  
  stylesheets:    
    - ../bootstrap/css/bootstrap.min.css
    #- ../less/bootstrap.less: {rel:  stylesheet/less }
    - bootstrap.css
  
  javascripts:
    - jquery/jquery-1.7.1.min.js
    - ../bootstrap/js/bootstrap.min.js
    - jenkins/modals.js
    #- less-1.2.2.min.js
  
  components:
    messages_flash: [default, messagesFlash]
    menu: [default, topMenu]
    footer: [default, footer]


